#! /usr/bin/env python3

from pathlib import Path
from subprocess import run
from sys import argv

autotest_path = Path(__file__).resolve().parent / 'submodules' / 'autotest' / 'autotest.py'

run(['python3', '-I', autotest_path] + argv[1:])